apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306      # Port du service (accès interne)
      targetPort: 3306  # Port sur lequel tourne l'application dans le Pod
  type: ClusterIP
