apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: mini-projet
  labels:
    app: mysql
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1 
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        envFrom:
        - secretRef:
            name: secret
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-volume
      volumes:
      - name: mysql-volume
        hostPath:                             # Une version PV/PVC sera créée une fois le README terminé
          path: /data-mysql
          type: DirectoryOrCreate
