apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: mini-projet
type: Opaque
data:
  mysql-root-password: d29yZHByZXNz
  mysql-database: d29yZHByZXNz
  mysql-user: d29yZHByZXNz
  mysql-password: d29yZHByZXNzMTIz
