apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  namespace: mini-projet
  labels:
    app: wordpress
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:6.7.2-php8.3
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: secret
        volumeMounts:
        - mountPath: /var/www/html
          name: wordpress-volume
      volumes:
      - name: wordpress-volume
        hostPath: 
          path: /data-wordpress
          type: DirectoryOrCreate

